//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MannusBackup.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MannusEntities : DbContext
    {
        public MannusEntities()
            : base("name=MannusEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ConfigurationProperty> backup_configuration { get; set; }
        public DbSet<Profile> backup_profile { get; set; }
        public DbSet<ProfileConfiguration> backup_profile_configuration { get; set; }
        public DbSet<ProfileProperty> backup_profileproperty { get; set; }
        public DbSet<backup_results> backup_results { get; set; }
    }
}
