//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MannusBackup.Database
{
    using System;
    
    public enum ProfileType : int
    {
        Client = 0,
        LocalStorage = 1,
        FtpStorage = 2,
        FlickrStorage = 3,
        CloudStorage = 4
    }
}
