//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MannusBackup.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileConfigurationGroup
    {
        public ProfileConfigurationGroup()
        {
            this.Configuration = new HashSet<ProfileConfiguration>();
        }
    
        public int id { get; set; }
        public int profileid { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
    
        public virtual Profile backup_profile { get; set; }
        public virtual ICollection<ProfileConfiguration> Configuration { get; set; }
    }
}
