//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MannusBackup.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileConfiguration
    {
        public int id { get; set; }
        public int configurationid { get; set; }
        public int profileid { get; set; }
        public string naam { get; set; }
        public string waarde { get; set; }
    
        public virtual ConfigurationProperty backup_configuration { get; set; }
        public virtual Profile backup_profile { get; set; }
    }
}
